---
title: "Interactive-Graphs"
author: "Prithvi Kinariwala"
date: "5/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r installation, eval=FALSE}
install.packages("ggplot2")
install.packages("dplyr")
install.packages("RColorBrewer")
```

Next you'll need to "activate" the individual libraries. 
```{r packages, results="hide", warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(plotly)
```

### What years saw the greatest amount of game releases?

```{r}
vgsales=read.csv("C:\\Users\\Prithvi Kinariwala\\Documents\\video-games-with-R\\vgsales.csv")
yeargames=vgsales
yeargames<-yeargames[!(yeargames$Year=="N/A" ),]
```
```{r Interactive-timegraph}
graph1 = ggplot(data = yeargames, mapping = aes(x =Year, fill= Platform))+
  geom_bar()+
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+
  labs(x = "Year", y="Number of Games Published",title = "Games Published 1980-2016")

ggplotly(graph1)
```
